# Generated by Django 4.0.4 on 2022-05-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('price', models.PositiveIntegerField()),
                ('image', models.URLField()),
                ('release_date', models.CharField(max_length=10)),
                ('lte_exists', models.BooleanField()),
                ('slug', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
