# Generated by Django 4.0.4 on 2022-05-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='slug',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
